package com.aliyun.openservices.log.util;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Random;

import org.junit.Test;

import static org.junit.Assert.assertArrayEquals;

public class LZ4EncoderTest {

    private static final byte[] LEGACY_RAW =
            "legacy-lz4-java-1.8.1 payload: Alibaba Cloud SLS compression compatibility"
                    .getBytes(StandardCharsets.UTF_8);
    // Generated by lz4-java 1.8.1 to guard compatibility with existing SLS payloads.
    private static final byte[] LEGACY_COMPRESSED = Base64.getDecoder().decode(
            "8S1sZWdhY3ktbHo0LWphdmEtMS44LjEgcGF5bG9hZDogQWxpYmFiYSBDbG91ZCBTTFMg"
                    + "Y29tcHJlc3Npb24MAJBhdGliaWxpdHk=");

    @Test
    public void testRoundTrip() throws Exception {
        byte[] randomData = new byte[64 * 1024];
        new Random(123456789L).nextBytes(randomData);

        assertRoundTrip(new byte[0]);
        assertRoundTrip(new byte[]{42});
        assertRoundTrip(LEGACY_RAW);
        assertRoundTrip(randomData);
    }

    @Test
    public void testDecompressesLegacyPayload() throws Exception {
        assertArrayEquals(
                LEGACY_RAW,
                LZ4Encoder.decompressFromLhLz4Chunk(LEGACY_COMPRESSED, LEGACY_RAW.length));
    }

    private static void assertRoundTrip(byte[] raw) throws Exception {
        byte[] compressed = LZ4Encoder.compressToLhLz4Chunk(raw);
        assertArrayEquals(raw, LZ4Encoder.decompressFromLhLz4Chunk(compressed, raw.length));
    }
}
